//
//  Token.swift
//  Defines the Token enum and any related structures to represent the tokens generated by the lexer.
//
//  Created by الشيخ عزام on 22/08/2024.
//

import Foundation

enum Token: Equatable {
    case keyword(String)
    case identifier(String)
    case number(Double)
    case string(String)
    case `operator`(String)
    case punctuation(String)
    case eof // Represents the end of the file/input
}
